//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishListItem
    {
        public int WishListID { get; set; }
        public int ProductID { get; set; }
    
        public virtual WishList WishList { get; set; }
    }
}
